name: ai_chat
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  lottie: ^2.7.0
  dio: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
   - assets/lotties/
   - assets/icons/

  fonts:
   - family: Nunito
     fonts:
       - asset: assets/fonts/Nunito/Nunito-Regular.ttf
         weight: 500
       - asset: assets/fonts/Nunito/Nunito-Medium.ttf
         weight: 600
       - asset: assets/fonts/Nunito/Nunito-Bold.ttf
         weight: 700

